/* offline cache for the Shine Cards home-screen app — pages: network first (fresh after a push), assets: cache first */
const V = 'shine-cards-f4f49fd67d', FILES = ["./", "./assets/logos/accenture.svg", "./assets/logos/amazon.svg", "./assets/logos/barclays.svg", "./assets/logos/byjus.svg", "./assets/logos/capgemini.svg", "./assets/logos/cognizant.svg", "./assets/logos/deloitte.svg", "./assets/logos/ey.svg", "./assets/logos/google.svg", "./assets/logos/groww.svg", "./assets/logos/hcl.svg", "./assets/logos/hsbc.svg", "./assets/logos/icici_bank.svg", "./assets/logos/infosys.svg", "./assets/logos/jpmorgan.svg", "./assets/logos/novartis.svg", "./assets/logos/ola.svg", "./assets/logos/phonepe.svg", "./assets/logos/postman.svg", "./assets/logos/rapido.svg", "./assets/logos/razorpay.svg", "./assets/logos/swiggy.svg", "./assets/logos/tcs.svg", "./assets/logos/wipro.svg", "./assets/logos/zerodha.svg", "./assets/logos/zomato.svg", "./components/bottom-sheet/bottom-sheet.css", "./components/bottom-sheet/bottom-sheet.js", "./components/notify/notify.css", "./components/notify/notify.js", "./components/search-modal/search-modal.css", "./components/search-modal/search-modal.js", "./components/sort-filter/sort-filter.css", "./components/sort-filter/sort-filter.js", "./css/app-home-logout.css", "./fonts/OFL-Inter.txt", "./fonts/OFL-PlusJakartaSans.txt", "./fonts/fonts.css", "./fonts/inter-latin-400-normal.woff2", "./fonts/inter-latin-500-normal.woff2", "./fonts/inter-latin-600-normal.woff2", "./fonts/inter-latin-700-normal.woff2", "./fonts/plus-jakarta-sans-latin-400-normal.woff2", "./fonts/plus-jakarta-sans-latin-500-normal.woff2", "./fonts/plus-jakarta-sans-latin-600-normal.woff2", "./fonts/plus-jakarta-sans-latin-700-normal.woff2", "./fonts/plus-jakarta-sans-latin-800-normal.woff2", "./fonts/plus-jakarta-sans-latin-ext-400-normal.woff2", "./fonts/plus-jakarta-sans-latin-ext-500-normal.woff2", "./fonts/plus-jakarta-sans-latin-ext-600-normal.woff2", "./fonts/plus-jakarta-sans-latin-ext-700-normal.woff2", "./fonts/plus-jakarta-sans-latin-ext-800-normal.woff2", "./icons/icon-180.png", "./icons/icon-192.png", "./icons/icon-512.png", "./index.html", "./js/app-home-logout.js", "./jsrp-logout.html", "./login-flow.html", "./login-welcome.html", "./manifest.webmanifest", "./native.js", "./splash.html"];
self.addEventListener('install', e => { e.waitUntil(caches.open(V).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== V).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const r = e.request; if (r.method !== 'GET' || new URL(r.url).origin !== location.origin) return;
  const page = r.mode === 'navigate' || r.destination === 'document';
  if (page) { e.respondWith(fetch(r).then(res => { const c = res.clone(); caches.open(V).then(x => x.put(r, c)); return res; })
                 .catch(() => caches.match(r, { ignoreSearch: true }).then(m => m || caches.match('./index.html')))); return; }
  e.respondWith(caches.match(r, { ignoreSearch: true }).then(m => m || fetch(r).then(res => { const c = res.clone(); caches.open(V).then(x => x.put(r, c)); return res; })));
});
